#############################################################################
# Makefile for building: ConfabulationEngine
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Feb 3 12:30:14 2015
# Project:  ConfabulationEngine.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile ConfabulationEngine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O3 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = text_processing/TextReader.cpp \
		text_processing/SentenceTokenizer.cpp \
		text_processing/NGramHandler.cpp \
		TemplateInstantiations.cpp \
		ConfabulationTest.cpp \
		Globals.cpp \
		SymbolMapping.cpp \
		KnowledgeBase.cpp \
		Module.cpp \
		MultiLevelOrganizer.cpp \
		ConfabulationBase.cpp \
		ForwardConfabulation.cpp \
		TwoLevelSimpleConfabulation.cpp 
OBJECTS       = TextReader.o \
		SentenceTokenizer.o \
		NGramHandler.o \
		TemplateInstantiations.o \
		ConfabulationTest.o \
		Globals.o \
		SymbolMapping.o \
		KnowledgeBase.o \
		Module.o \
		MultiLevelOrganizer.o \
		ConfabulationBase.o \
		ForwardConfabulation.o \
		TwoLevelSimpleConfabulation.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ConfabulationEngine.pro
QMAKE_TARGET  = ConfabulationEngine
DESTDIR       = 
TARGET        = ConfabulationEngine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ConfabulationEngine.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile ConfabulationEngine.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile ConfabulationEngine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ConfabulationEngine1.0.0 || $(MKDIR) .tmp/ConfabulationEngine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ConfabulationEngine1.0.0/ && (cd `dirname .tmp/ConfabulationEngine1.0.0` && $(TAR) ConfabulationEngine1.0.0.tar ConfabulationEngine1.0.0 && $(COMPRESS) ConfabulationEngine1.0.0.tar) && $(MOVE) `dirname .tmp/ConfabulationEngine1.0.0`/ConfabulationEngine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ConfabulationEngine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

TextReader.o: text_processing/TextReader.cpp text_processing/TextReader.h \
		Globals.h \
		text_processing/SentenceTokenizer.h \
		utils/Utils.h \
		Dbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextReader.o text_processing/TextReader.cpp

SentenceTokenizer.o: text_processing/SentenceTokenizer.cpp text_processing/SentenceTokenizer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SentenceTokenizer.o text_processing/SentenceTokenizer.cpp

NGramHandler.o: text_processing/NGramHandler.cpp text_processing/NGramHandler.h \
		SymbolMapping.h \
		utils/Utils.h \
		Dbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NGramHandler.o text_processing/NGramHandler.cpp

TemplateInstantiations.o: TemplateInstantiations.cpp TemplateInstantiations.h \
		sparse_structures/DOKExcitationVector.hpp \
		utils/Utils.h \
		sparse_structures/IExcitationVector.hpp \
		sparse_structures/DOKLinksMatrix.hpp \
		sparse_structures/IKnowledgeLinks.hpp \
		sparse_structures/CSRLinksMatrix.hpp \
		utils/HashTrieNode.hpp \
		utils/HashTrie.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TemplateInstantiations.o TemplateInstantiations.cpp

ConfabulationTest.o: ConfabulationTest.cpp Globals.h \
		ConfabulationTest.h \
		text_processing/SentenceTokenizer.h \
		SymbolMapping.h \
		text_processing/NGramHandler.h \
		text_processing/TextReader.h \
		sparse_structures/DOKExcitationVector.hpp \
		utils/Utils.h \
		sparse_structures/IExcitationVector.hpp \
		sparse_structures/DOKLinksMatrix.hpp \
		sparse_structures/IKnowledgeLinks.hpp \
		sparse_structures/CSRLinksMatrix.hpp \
		utils/HashTrie.hpp \
		utils/HashTrieNode.hpp \
		ForwardConfabulation.h \
		ConfabulationBase.h \
		MultiLevelOrganizer.h \
		Module.h \
		KnowledgeBase.h \
		TwoLevelSimpleConfabulation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfabulationTest.o ConfabulationTest.cpp

Globals.o: Globals.cpp Globals.h \
		text_processing/NGramHandler.h \
		SymbolMapping.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Globals.o Globals.cpp

SymbolMapping.o: SymbolMapping.cpp SymbolMapping.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SymbolMapping.o SymbolMapping.cpp

KnowledgeBase.o: KnowledgeBase.cpp KnowledgeBase.h \
		sparse_structures/DOKLinksMatrix.hpp \
		sparse_structures/DOKExcitationVector.hpp \
		utils/Utils.h \
		sparse_structures/IExcitationVector.hpp \
		sparse_structures/IKnowledgeLinks.hpp \
		sparse_structures/CSRLinksMatrix.hpp \
		SymbolMapping.h \
		Globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KnowledgeBase.o KnowledgeBase.cpp

Module.o: Module.cpp Module.h \
		sparse_structures/IExcitationVector.hpp \
		SymbolMapping.h \
		Globals.h \
		utils/Utils.h \
		sparse_structures/DOKExcitationVector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Module.o Module.cpp

MultiLevelOrganizer.o: MultiLevelOrganizer.cpp MultiLevelOrganizer.h \
		SymbolMapping.h \
		utils/HashTrie.hpp \
		utils/HashTrieNode.hpp \
		utils/Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultiLevelOrganizer.o MultiLevelOrganizer.cpp

ConfabulationBase.o: ConfabulationBase.cpp Globals.h \
		ConfabulationBase.h \
		text_processing/TextReader.h \
		text_processing/NGramHandler.h \
		SymbolMapping.h \
		MultiLevelOrganizer.h \
		utils/HashTrie.hpp \
		utils/HashTrieNode.hpp \
		Module.h \
		sparse_structures/IExcitationVector.hpp \
		KnowledgeBase.h \
		sparse_structures/DOKLinksMatrix.hpp \
		sparse_structures/DOKExcitationVector.hpp \
		utils/Utils.h \
		sparse_structures/IKnowledgeLinks.hpp \
		sparse_structures/CSRLinksMatrix.hpp \
		Dbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfabulationBase.o ConfabulationBase.cpp

ForwardConfabulation.o: ForwardConfabulation.cpp ForwardConfabulation.h \
		ConfabulationBase.h \
		text_processing/TextReader.h \
		text_processing/NGramHandler.h \
		SymbolMapping.h \
		MultiLevelOrganizer.h \
		utils/HashTrie.hpp \
		utils/HashTrieNode.hpp \
		Module.h \
		sparse_structures/IExcitationVector.hpp \
		KnowledgeBase.h \
		sparse_structures/DOKLinksMatrix.hpp \
		sparse_structures/DOKExcitationVector.hpp \
		utils/Utils.h \
		sparse_structures/IKnowledgeLinks.hpp \
		sparse_structures/CSRLinksMatrix.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ForwardConfabulation.o ForwardConfabulation.cpp

TwoLevelSimpleConfabulation.o: TwoLevelSimpleConfabulation.cpp TwoLevelSimpleConfabulation.h \
		ForwardConfabulation.h \
		ConfabulationBase.h \
		text_processing/TextReader.h \
		text_processing/NGramHandler.h \
		SymbolMapping.h \
		MultiLevelOrganizer.h \
		utils/HashTrie.hpp \
		utils/HashTrieNode.hpp \
		Module.h \
		sparse_structures/IExcitationVector.hpp \
		KnowledgeBase.h \
		sparse_structures/DOKLinksMatrix.hpp \
		sparse_structures/DOKExcitationVector.hpp \
		utils/Utils.h \
		sparse_structures/IKnowledgeLinks.hpp \
		sparse_structures/CSRLinksMatrix.hpp \
		Globals.h \
		Dbg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TwoLevelSimpleConfabulation.o TwoLevelSimpleConfabulation.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

